# CI Trigger on main branch
trigger:
  branches:
    include:
    - main
    - release/3.1.4xx
  paths:
    include:
    - eng/Version.Details.xml

# Trigger builds for PR's targeting main
pr:
  branches:
    include:
    - main
  paths:
    exclude: # don't trigger the CI if only a doc file was changed
    - docs/*
    - eng/common/README.md
    - src/benchmarks/micro/Serializers/README.md
    - src/benchmarks/micro/README.md
    - src/benchmarks/real-world/JitBench/README.md
    - src/benchmarks/real-world/Microsoft.ML.Benchmarks/Input/README.md
    - src/tools/ResultsComparer/README.md
    - README.md

schedules:
- cron: "0 */12 * * *"
  displayName: Every 12 hours build
  branches:
    include:
    - main
    - release/3.1.4xx
  always: true

  # Ubuntu 1804 Arm64 micro benchmarks
  - template: /eng/performance/benchmark_jobs.yml
    parameters:
      osName: ubuntu
      osVersion: 1804
      kind: micro
      architecture: arm64
      pool: Hosted Ubuntu 1604
      machinePool: Open
      queue: Ubuntu.1804.Arm64.perf
      csproj: src\benchmarks\micro\MicroBenchmarks.csproj
      runCategories: 'runtime libraries' 
      channels:
        - main
        - release/3.1.3xx

  # Windows Arm64 micro benchmarks
  - template: /eng/performance/benchmark_jobs.yml
    parameters:
      osName: windows
      osVersion: 10.19041
      kind: micro
      architecture: arm64
      pool: Hosted VS2017
      machinePool: Open
      queue: Windows.10.Arm64.perf.surf
      csproj: src\benchmarks\micro\MicroBenchmarks.csproj
      runCategories: 'runtime libraries' 
      channels:
        - main
        - release/3.1.3xx

